#!/bin/bash

if ! command -v pyenv &> /dev/null; then
    echo "pyenv не установлен. Устанавливаем pyenv..."

    if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
        libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
        liblzma-dev python-openssl git
    elif command -v yum &> /dev/null; then
        sudo yum groupinstall 'Development Tools'
        sudo yum install -y zlib-devel bzip2 bzip2-devel readline-devel sqlite \
        sqlite-devel openssl-devel xz xz-devel libffi-devel findutils
    else
        echo "Не удалось определить пакетный менеджер. Пожалуйста, установите зависимости вручную."
        exit 1
    fi

    curl https://pyenv.run | bash

    if [ -f ~/.bashrc ]; then
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
        echo 'eval "$(pyenv init -)"' >> ~/.bashrc
        source ~/.bashrc
    elif [ -f ~/.zshrc ]; then
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.zshrc
        echo 'eval "$(pyenv init --path)"' >> ~/.zshrc
        echo 'eval "$(pyenv init -)"' >> ~/.zshrc
        source ~/.zshrc
    else
        echo "Не удалось найти .bashrc или .zshrc. Пожалуйста, добавьте pyenv вручную."
        exit 1
    fi
fi