#!/bin/bash

user_name=$(whoami)
python_ver="3.10.14"
env_name="ansible-venv"
pyenv_home="/home/$user_name/.pyenv"
pyenv_env="$pyenv_home/versions/$env_name"
pyenv_bin="$pyenv_home/bin/pyenv"

rm -rf $pyenv_home

curl https://pyenv.run | bash

$pyenv_bin install $python_ver
$pyenv_bin virtualenv $python_ver $env_name
source $pyenv_env/bin/activate

pip install ansible-core==2.12
pip install netaddr
pip install jinja2==3.0
pip install markupsafe==2.0.1
pip install jmespath
# pip install psycopg2
ansible-galaxy collection install community.general
ansible-galaxy collection install ansible.posix
ansible-galaxy collection install community.crypto
ansible-galaxy collection install community.postgresql
ansible-galaxy collection install ansible.utils
deactivate

echo "alias activate='source $pyenv_env/bin/activate'" >> ~/.bashrc
source ~/.bashrc
echo 'Перед работой с Ansible нужно активировать виртуальную среду! Это можно сделать командой: "activate"'
